apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: odoo-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: odoo-secrets
    creationPolicy: Owner
  data:
    - secretKey: db_host
      remoteRef:
        key: kv/odoo/dev
        property: db_host
    - secretKey: db_port
      remoteRef:
        key: kv/odoo/dev
        property: db_port
    - secretKey: db_user
      remoteRef:
        key: kv/odoo/dev
        property: db_user
    - secretKey: db_password
      remoteRef:
        key: kv/odoo/dev
        property: db_password
    - secretKey: db_name
      remoteRef:
        key: kv/odoo/dev
        property: db_name
    - secretKey: db_sslmode
      remoteRef:
        key: kv/odoo/dev
        property: db_sslmode
    - secretKey: admin_password
      remoteRef:
        key: kv/odoo/dev
        property: admin_password
