apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: odoo
spec:
  minReplicas: 4
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
