apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-proxy
spec:
  template:
    spec:
      containers:
        - name: oauth2-proxy
          args:
            - --redirect-url=https://odoo.dev.yourdomain.tld/oauth2/callback
            - --oidc-issuer-url=https://keycloak.dev.yourdomain.tld/realms/odoo
